# ============================================================
#                         Load Balancer
# ============================================================
apiVersion: v1
kind: Service
metadata:
  name: my-load-balancer
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-default-proxy-protocol: "none"
    service.beta.kubernetes.io/linode-loadbalancer-preserve: "true"
    #    service.beta.kubernetes.io/linode-loadbalancer-hostname-only-ingress: "true"
  namespace: nginx-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: nginx-ingress

---
